export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import redis from '@/lib/redis';
import { verifyToken } from '@/lib/auth';
import type { Receipt, OrderItem, PaymentMethod } from '@/types/order';

// GET /api/pos/receipts?orderId=...
export async function GET(request: Request) {
  try {
    const authHeader = request.headers.get('authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.substring(7);
    const { payload, error } = verifyToken(token);
    if (error || !payload) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const orderId = searchParams.get('orderId');

    if (!orderId) {
      return NextResponse.json({ error: 'orderId query parameter is required' }, { status: 400 });
    }

    const orderData = await redis.hGetAll(`order:${orderId}`);
    if (Object.keys(orderData).length === 0) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    const paymentMethod = (orderData.paymentMethod || 'cash') as PaymentMethod;
    const receipt: Receipt = {
      orderId: orderData.id,
      date: orderData.createdAt,
      cashierId: orderData.userId,
      items: JSON.parse(orderData.items || '[]') as OrderItem[],
      totalAmount: parseFloat(orderData.totalAmount || '0'),
      paymentMethod,
      notes: orderData.notes || 'Receipt generated by PPC Stock Management'
    };

    return NextResponse.json({ receipt });
  } catch (error) {
    console.error('Error fetching receipt:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
